# Generated by Django 5.0.3 on 2024-03-17 12:47

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task1', '0002_alter_user_is_deleted'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('everything', django.db.models.manager.Manager()),
            ],
        ),
    ]
