# Generated by Django 5.0.3 on 2024-03-17 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task1', '0003_alter_user_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
