# Generated by Django 5.0.3 on 2024-03-17 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task1', '0005_alter_user_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.AlterUniqueTogether(
            name='user',
            unique_together={('username', 'is_deleted')},
        ),
    ]
