# Generated by Django 5.0.3 on 2024-03-19 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companies1', to='project1.company')),
                ('jobseekers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobseekers1', to='project1.jobseekers')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancies1', to='project1.vacancy')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
