# Generated by Django 5.0.3 on 2024-03-19 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project1', '0002_statistics'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Statistics',
        ),
    ]
